use_frameworks!

platform :ios, '11.0'

target 'LvykFoundation_Example' do
  pod 'LvykFoundation', :path => '../'
  
  pod 'Moya'
  pod 'BigInt'
  pod 'Cache'

  target 'LvykFoundation_Tests' do
    inherit! :search_paths

    
  end
end
